### ISSUE TITLE
UI cleanup does not occur

### ISSUE THREAD

**Issue by KacperMucha** [ARMataTeam/ARMata#12]
On subsequent file open UI is not cleared from previous template data.

**Comment by kamil-mrzyglod** [comment]
This should be fixed thanks to #10 - could you fetch the latest version and confirm this is still an issue?

**Comment by KacperMucha** [comment]
Now it looks ok. But there is another problem. If a template is too large it cannot be scrolled down. :) I'll create a new issue for that.

**Comment by kamil-mrzyglod** [comment]
True, figured this out today :) Closing then.
