### ISSUE TITLE
Build server

### ISSUE THREAD

**Issue by kamil-mrzyglod** [ARMataTeam/ARMata#4]
We're going to need a server, which will build the application and run tests etc. Consider both free and commercial solutions.

**Comment by KacperMucha** [comment]
I have experience with VSTS mainly, but learning Jenkins for example shouldn't be a problem. But what are we aiming for? One global build agent or many build agents located on developer machines etc.? Former option would probably introduce some costs, latter would require to maintain configuration between all build agents.

**Comment by kamil-mrzyglod** [comment]
@KacperMucha We could try multiple ones like Travis CI and AppVeyor, which are currently pre-configured and I'm working on builds passing.

I think that if needed, we could introduce other build agents like VSTS/Jenkins/TeamCity to actually publish things and automate everything, Travis and AppVeyor are OK for running a simple pipeline and tests.
