### ISSUE TITLE
Should we add package-lock.json to .gitignore?

### ISSUE THREAD

**Issue by BienioM** [ARMataTeam/ARMata#86]
#83 ..as @kamil-mrzyglod mention.
Usually, I have added 'block' rule to gitignore, but this is not a simple decision:
(btw., i thought that this rule has already exist)

1. [SO](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5)
2. https://docs.npmjs.com/files/package-lock.json

> This file is intended to be committed into source repositories.

Another option is to create file .npmrc with:

> package-lock=false

I leave it to your judgment @kamil-mrzyglod.
Do you completely disable creation on your machine, by set npm config rule `npm config set package-lock false` ?

**Comment by kamil-mrzyglod** [comment]
Since it's more like NPM feature I'd advise not to include it for now(especially that many people mention, that it introduces lots of noise into a repository).

If this changes any time soon, we'll reconsider our approach.
